baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Noreast\'R Conference - Summer 2018 - Providence, RI"
theme = "minimal"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Keynote"
    url = "/keynote/
[[menu.main]]
    name = "Schedule"
    url = "/schedule/"
[[menu.main]]
    name = "Code of Conduct"
    url = "/codeofconduct/"
    

[params]
    description = "A regional #rstats conference for the Northeastern United States"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

