baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Nor'eastR Conference"
theme = "minimal"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
backgroundImage = "https://github.com/noreastrconf/noreastrconf.github.io/blob/master/content/ri-coast.jpg?raw=true"


[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name="Home"
    url="/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Schedule"
    url = "/schedule/"
    weight = 3
[[menu.main]]
    name = "Code of Conduct"
    url = "/codeofconduct/"
    weight = 4
[[menu.main]]
    name = "Sponsors"
    url = "/sponsors/"
    weight = 5
[[menu.main]]
    name = "Venue and Travel Info"
    url = "/venue/"
    weight = 6
[[menu.main]]
    name = "Registration"
    url = "https://www.regonline.com/noreastr"
    weight = 7

[[menu.icon]]
    url = "mailto:noreastrconf@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/noreastrconf/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/noreastrconf/"
    name = "twitter"
    weight = 3
    

[params]
    description = "A one day #rstats conference - Friday, October 26, 2018 - Providence, RI."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "https://github.com/noreastrconf/hex_logo/blob/master/Noreast'R(viridis).png?raw=true"
    width = 50
    height = 50
    alt = "Logo"
    
    [[params.sponsors]]
        name = "Microsoft Azure"
        logo = "/MS-Azure_logo_horiz_c-gray_rgb_cropped.png"
        url = "https://developer.microsoft.com/en-us/advocates/index.html"
        twitter = "azureadvocates"
        level = "gold"
        width = 205
        
    [[params.sponsors]]
        name = "RStudio"
        logo = "/RStudio-Logo-Blue-Gray.jpg"
        url = "https://www.rstudio.com/"
        twitter = "rstudio"
        level = "gold"
        width = 140
        
    [[params.sponsors]]
        name = "Manning Publications"
        logo = "/Manninglogo_outline.png"
        url = "https://www.manning.com/"
        twitter = "ManningBooks"
        level = "bronze"
        width = 150
    
    [[params.sponsors]]
        name = "Coastal Institute"
        logo = "/ci_logo_from_web.jpg"
        url = "https://ci.uri.edu"
        twitter = "uri_coastalinst"
        level = "host"
        width = 105
    

    
    



